[project]
name = "expense-tracker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.14.1",
    "fastapi[standard]>=0.115.8",
    "sqlalchemy>=2.0.37",
]
